/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000101) */

module FSM_Gray_Code(ip, clk, rst, op);
  input [1:0] ip;
  wire [1:0] ip;
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [1:0] op;
  wire [1:0] op;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire [2:0] next_state;
  wire [2:0] state;
  INV_X1 _27_ (
    .A(ip[0]),
    .ZN(_06_)
  );
  INV_X1 _28_ (
    .A(ip[1]),
    .ZN(_07_)
  );
  INV_X1 _29_ (
    .A(rst),
    .ZN(_03_)
  );
  XNOR2_X1 _30_ (
    .A(ip[0]),
    .B(ip[1]),
    .ZN(_08_)
  );
  NOR3_X1 _31_ (
    .A1(_02_),
    .A2(state[2]),
    .A3(state[1]),
    .ZN(_09_)
  );
  NOR3_X1 _32_ (
    .A1(_02_),
    .A2(_01_),
    .A3(state[2]),
    .ZN(_10_)
  );
  AOI21_X1 _33_ (
    .A(_09_),
    .B1(_10_),
    .B2(ip[1]),
    .ZN(_11_)
  );
  NOR3_X1 _34_ (
    .A1(state[0]),
    .A2(state[2]),
    .A3(state[1]),
    .ZN(_12_)
  );
  NOR2_X1 _35_ (
    .A1(ip[0]),
    .A2(ip[1]),
    .ZN(_13_)
  );
  NOR3_X1 _36_ (
    .A1(_01_),
    .A2(state[0]),
    .A3(state[2]),
    .ZN(_14_)
  );
  INV_X1 _37_ (
    .A(_14_),
    .ZN(_15_)
  );
  AOI22_X1 _38_ (
    .A1(ip[1]),
    .A2(_12_),
    .B1(_13_),
    .B2(_14_),
    .ZN(_16_)
  );
  OAI21_X1 _39_ (
    .A(_16_),
    .B1(_11_),
    .B2(_08_),
    .ZN(next_state[0])
  );
  NOR3_X1 _40_ (
    .A1(_01_),
    .A2(state[0]),
    .A3(_00_),
    .ZN(_17_)
  );
  NAND3_X1 _41_ (
    .A1(ip[0]),
    .A2(ip[1]),
    .A3(_17_),
    .ZN(_18_)
  );
  AOI21_X1 _42_ (
    .A(_14_),
    .B1(_12_),
    .B2(_06_),
    .ZN(_19_)
  );
  NAND2_X1 _43_ (
    .A1(_07_),
    .A2(_09_),
    .ZN(_20_)
  );
  NAND3_X1 _44_ (
    .A1(ip[0]),
    .A2(_07_),
    .A3(_10_),
    .ZN(_21_)
  );
  NAND4_X1 _45_ (
    .A1(_18_),
    .A2(_19_),
    .A3(_20_),
    .A4(_21_),
    .ZN(op[0])
  );
  AOI21_X1 _46_ (
    .A(_09_),
    .B1(_12_),
    .B2(ip[1]),
    .ZN(_22_)
  );
  NAND2_X1 _47_ (
    .A1(_08_),
    .A2(_17_),
    .ZN(_23_)
  );
  AOI21_X1 _48_ (
    .A(_14_),
    .B1(_17_),
    .B2(_08_),
    .ZN(_24_)
  );
  OAI21_X1 _49_ (
    .A(_10_),
    .B1(ip[1]),
    .B2(ip[0]),
    .ZN(_25_)
  );
  OAI211_X1 _50_ (
    .A(_24_),
    .B(_25_),
    .C1(_06_),
    .C2(_22_),
    .ZN(next_state[1])
  );
  OAI211_X1 _51_ (
    .A(_21_),
    .B(_23_),
    .C1(_08_),
    .C2(_15_),
    .ZN(next_state[2])
  );
  AOI221_X1 _52_ (
    .A(_09_),
    .B1(_14_),
    .B2(_08_),
    .C1(_17_),
    .C2(ip[1]),
    .ZN(_26_)
  );
  INV_X1 _53_ (
    .A(_26_),
    .ZN(op[1])
  );
  INV_X1 _54_ (
    .A(rst),
    .ZN(_04_)
  );
  INV_X1 _55_ (
    .A(rst),
    .ZN(_05_)
  );
  DFFR_X1 _56_ (
    .CK(clk),
    .D(next_state[0]),
    .Q(state[0]),
    .QN(_02_),
    .RN(_03_)
  );
  DFFR_X1 _57_ (
    .CK(clk),
    .D(next_state[1]),
    .Q(state[1]),
    .QN(_01_),
    .RN(_04_)
  );
  DFFR_X1 _58_ (
    .CK(clk),
    .D(next_state[2]),
    .Q(state[2]),
    .QN(_00_),
    .RN(_05_)
  );
endmodule
