/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000101) */

module FSM_One_Hot(ip, clk, rst, op);
  input [1:0] ip;
  wire [1:0] ip;
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [1:0] op;
  wire [1:0] op;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire [4:0] next_state;
  wire [4:0] state;
  INV_X1 _37_ (
    .A(ip[0]),
    .ZN(_10_)
  );
  INV_X1 _38_ (
    .A(ip[1]),
    .ZN(_11_)
  );
  INV_X1 _39_ (
    .A(rst),
    .ZN(_05_)
  );
  NOR2_X1 _40_ (
    .A1(_10_),
    .A2(ip[1]),
    .ZN(_12_)
  );
  OR2_X1 _41_ (
    .A1(state[3]),
    .A2(state[2]),
    .ZN(_13_)
  );
  NOR4_X1 _42_ (
    .A1(state[4]),
    .A2(state[0]),
    .A3(_00_),
    .A4(_13_),
    .ZN(_14_)
  );
  NOR2_X1 _43_ (
    .A1(ip[0]),
    .A2(ip[1]),
    .ZN(_15_)
  );
  XOR2_X1 _44_ (
    .A(ip[0]),
    .B(ip[1]),
    .Z(_16_)
  );
  OR2_X1 _45_ (
    .A1(state[1]),
    .A2(state[0]),
    .ZN(_17_)
  );
  NOR3_X1 _46_ (
    .A1(_01_),
    .A2(_13_),
    .A3(_17_),
    .ZN(_18_)
  );
  NAND3_X1 _47_ (
    .A1(ip[0]),
    .A2(ip[1]),
    .A3(_18_),
    .ZN(_19_)
  );
  NOR4_X1 _48_ (
    .A1(state[4]),
    .A2(state[1]),
    .A3(_03_),
    .A4(_13_),
    .ZN(_20_)
  );
  INV_X1 _49_ (
    .A(_20_),
    .ZN(_21_)
  );
  NOR4_X1 _50_ (
    .A1(_04_),
    .A2(state[3]),
    .A3(state[4]),
    .A4(_17_),
    .ZN(_22_)
  );
  NAND3_X1 _51_ (
    .A1(_10_),
    .A2(ip[1]),
    .A3(_22_),
    .ZN(_23_)
  );
  AOI22_X1 _52_ (
    .A1(_12_),
    .A2(_14_),
    .B1(_15_),
    .B2(_20_),
    .ZN(_24_)
  );
  NAND3_X1 _53_ (
    .A1(_19_),
    .A2(_23_),
    .A3(_24_),
    .ZN(next_state[2])
  );
  NOR3_X1 _54_ (
    .A1(_14_),
    .A2(_20_),
    .A3(_22_),
    .ZN(_25_)
  );
  NOR3_X1 _55_ (
    .A1(_10_),
    .A2(_11_),
    .A3(_25_),
    .ZN(next_state[0])
  );
  NOR4_X1 _56_ (
    .A1(state[4]),
    .A2(state[2]),
    .A3(_02_),
    .A4(_17_),
    .ZN(_26_)
  );
  INV_X1 _57_ (
    .A(_26_),
    .ZN(_27_)
  );
  NAND3_X1 _58_ (
    .A1(ip[0]),
    .A2(ip[1]),
    .A3(_26_),
    .ZN(_28_)
  );
  AOI22_X1 _59_ (
    .A1(_11_),
    .A2(_14_),
    .B1(_22_),
    .B2(_12_),
    .ZN(_29_)
  );
  AOI21_X1 _60_ (
    .A(_20_),
    .B1(_18_),
    .B2(_10_),
    .ZN(_30_)
  );
  NAND3_X1 _61_ (
    .A1(_28_),
    .A2(_29_),
    .A3(_30_),
    .ZN(op[0])
  );
  NOR2_X1 _62_ (
    .A1(_14_),
    .A2(_18_),
    .ZN(_31_)
  );
  NOR3_X1 _63_ (
    .A1(ip[0]),
    .A2(_11_),
    .A3(_31_),
    .ZN(next_state[1])
  );
  AOI22_X1 _64_ (
    .A1(_16_),
    .A2(_20_),
    .B1(_22_),
    .B2(_12_),
    .ZN(_32_)
  );
  OAI21_X1 _65_ (
    .A(_32_),
    .B1(_27_),
    .B2(_16_),
    .ZN(next_state[3])
  );
  OR4_X1 _66_ (
    .A1(_14_),
    .A2(_20_),
    .A3(_22_),
    .A4(_26_),
    .ZN(_33_)
  );
  OAI21_X1 _67_ (
    .A(_15_),
    .B1(_22_),
    .B2(_14_),
    .ZN(_34_)
  );
  AOI22_X1 _68_ (
    .A1(_11_),
    .A2(_18_),
    .B1(_26_),
    .B2(_16_),
    .ZN(_35_)
  );
  OAI211_X1 _69_ (
    .A(_34_),
    .B(_35_),
    .C1(_18_),
    .C2(_33_),
    .ZN(next_state[4])
  );
  AOI21_X1 _70_ (
    .A(_14_),
    .B1(_26_),
    .B2(ip[1]),
    .ZN(_36_)
  );
  OAI21_X1 _71_ (
    .A(_36_),
    .B1(_21_),
    .B2(_16_),
    .ZN(op[1])
  );
  INV_X1 _72_ (
    .A(rst),
    .ZN(_06_)
  );
  INV_X1 _73_ (
    .A(rst),
    .ZN(_07_)
  );
  INV_X1 _74_ (
    .A(rst),
    .ZN(_08_)
  );
  INV_X1 _75_ (
    .A(rst),
    .ZN(_09_)
  );
  DFFR_X1 _76_ (
    .CK(clk),
    .D(next_state[0]),
    .Q(state[0]),
    .QN(_03_),
    .RN(_06_)
  );
  DFFR_X1 _77_ (
    .CK(clk),
    .D(next_state[1]),
    .Q(state[1]),
    .QN(_00_),
    .RN(_09_)
  );
  DFFR_X1 _78_ (
    .CK(clk),
    .D(next_state[2]),
    .Q(state[2]),
    .QN(_04_),
    .RN(_05_)
  );
  DFFR_X1 _79_ (
    .CK(clk),
    .D(next_state[3]),
    .Q(state[3]),
    .QN(_02_),
    .RN(_07_)
  );
  DFFS_X1 _80_ (
    .CK(clk),
    .D(next_state[4]),
    .Q(state[4]),
    .QN(_01_),
    .SN(_08_)
  );
endmodule
